services:
    gateway:
        build: ./services/gateway
        environment:
            - PORT=${SERVER_PORT}
            - STORAGE_HOST=${STORAGE_HOST}
        restart: always
        ports:
            - 80:${SERVER_PORT}
        networks:
            - storage

    storage:
        build: ./services/storage
        environment:
            - PORT=${SERVER_PORT}
        restart: always
        volumes:
            - ./storage:/app/storage:ro
        networks:
            - storage

networks:
    storage:
        driver: bridge
