services:
    gateway:
        build: ./services/gateway
        environment:
            - PORT=${SERVER_PORT}
            - STORAGE_HOST=${STORAGE_HOST}
        ports:
            - 80:${SERVER_PORT}
        networks:
            - storage
        restart: always

    storage:
        build: ./services/storage
        environment:
            - PORT=${SERVER_PORT}
        volumes:
            - ./storage:/app/storage:ro
        networks:
            - storage
        restart: always

networks:
    storage:
        driver: bridge
