services:
    gateway:
        build: ./services/gateway
        environment:
            PORT: ${SERVER_PORT}
            STORAGE_HOST: ${STORAGE_HOST}
            USER_HOST: ${USER_HOST}
        ports:
            - 80:${SERVER_PORT}
        networks:
            - storage
            - user
        restart: always

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
        networks:
            - user-postgres

    storage:
        build: ./services/storage
        environment:
            PORT: ${SERVER_PORT}
        volumes:
            - ./storage:/app/storage:ro
        networks:
            - storage
        restart: always

    user:
        build: ./services/user
        environment:
            PORT: ${SERVER_PORT}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_HOST: ${USER_POSTGRES_HOST}
        networks:
            - user-postgres
            - user
        restart: always
        depends_on:
            - user-postgres

    user-postgres:
        image: postgres:17-alpine
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        networks:
            - user-postgres
        volumes:
            - user-postgres:/var/lib/postgresql/data
            - ./user-postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
            interval: 1m30s
            timeout: 30s
            retries: 5
            start_period: 30s

networks:
    storage:
        driver: bridge
    user-postgres:
        driver: bridge
    user:
        driver: bridge

volumes:
    user-postgres: null
