// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: protobuf/path.proto

package pathpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreatePathRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int32            `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId     int32            `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Name       string           `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Public     bool             `protobuf:"varint,4,opt,name=public,proto3" json:"public,omitempty"`
	Steps      int32            `protobuf:"varint,5,opt,name=steps,proto3" json:"steps,omitempty"`
	OtherStats map[string]int32 `protobuf:"bytes,6,rep,name=other_stats,json=otherStats,proto3" json:"other_stats,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (x *CreatePathRequest) Reset() {
	*x = CreatePathRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_path_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePathRequest) ProtoMessage() {}

func (x *CreatePathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_path_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePathRequest.ProtoReflect.Descriptor instead.
func (*CreatePathRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_path_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePathRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreatePathRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreatePathRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePathRequest) GetPublic() bool {
	if x != nil {
		return x.Public
	}
	return false
}

func (x *CreatePathRequest) GetSteps() int32 {
	if x != nil {
		return x.Steps
	}
	return 0
}

func (x *CreatePathRequest) GetOtherStats() map[string]int32 {
	if x != nil {
		return x.OtherStats
	}
	return nil
}

type CreatePathResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreatePathResponse) Reset() {
	*x = CreatePathResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_path_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePathResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePathResponse) ProtoMessage() {}

func (x *CreatePathResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_path_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePathResponse.ProtoReflect.Descriptor instead.
func (*CreatePathResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_path_proto_rawDescGZIP(), []int{1}
}

var File_protobuf_path_proto protoreflect.FileDescriptor

var file_protobuf_path_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x70, 0x61, 0x74, 0x68, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70, 0x61, 0x74, 0x68, 0x70, 0x62, 0x22, 0x88, 0x02,
	0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x61, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x06, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x65, 0x70, 0x73,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x74, 0x65, 0x70, 0x73, 0x12, 0x4a, 0x0a,
	0x0b, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x73, 0x18, 0x06, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x29, 0x2e, 0x70, 0x61, 0x74, 0x68, 0x70, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x50, 0x61, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x4f, 0x74,
	0x68, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0a, 0x6f,
	0x74, 0x68, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x73, 0x1a, 0x3d, 0x0a, 0x0f, 0x4f, 0x74, 0x68,
	0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x14, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x50, 0x61, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x54,
	0x0a, 0x0b, 0x50, 0x61, 0x74, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x45, 0x0a,
	0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x61, 0x74, 0x68, 0x12, 0x19, 0x2e, 0x70, 0x61,
	0x74, 0x68, 0x70, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x61, 0x74, 0x68, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x70, 0x61, 0x74, 0x68, 0x70, 0x62, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x61, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x70, 0x61, 0x74, 0x68, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobuf_path_proto_rawDescOnce sync.Once
	file_protobuf_path_proto_rawDescData = file_protobuf_path_proto_rawDesc
)

func file_protobuf_path_proto_rawDescGZIP() []byte {
	file_protobuf_path_proto_rawDescOnce.Do(func() {
		file_protobuf_path_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_path_proto_rawDescData)
	})
	return file_protobuf_path_proto_rawDescData
}

var file_protobuf_path_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protobuf_path_proto_goTypes = []interface{}{
	(*CreatePathRequest)(nil),  // 0: pathpb.CreatePathRequest
	(*CreatePathResponse)(nil), // 1: pathpb.CreatePathResponse
	nil,                        // 2: pathpb.CreatePathRequest.OtherStatsEntry
}
var file_protobuf_path_proto_depIdxs = []int32{
	2, // 0: pathpb.CreatePathRequest.other_stats:type_name -> pathpb.CreatePathRequest.OtherStatsEntry
	0, // 1: pathpb.PathService.CreatePath:input_type -> pathpb.CreatePathRequest
	1, // 2: pathpb.PathService.CreatePath:output_type -> pathpb.CreatePathResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protobuf_path_proto_init() }
func file_protobuf_path_proto_init() {
	if File_protobuf_path_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_path_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePathRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_path_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePathResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_path_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuf_path_proto_goTypes,
		DependencyIndexes: file_protobuf_path_proto_depIdxs,
		MessageInfos:      file_protobuf_path_proto_msgTypes,
	}.Build()
	File_protobuf_path_proto = out.File
	file_protobuf_path_proto_rawDesc = nil
	file_protobuf_path_proto_goTypes = nil
	file_protobuf_path_proto_depIdxs = nil
}
